### PR TITLE
HV-872 optional relaxation of parameter validation

### PR DESCRIPTION
**Pull request by ctabeckey**
Started from version 5.0, rebased to master and merged to there. Built and unit tested.

### CODE REVIEW

**Comment by hferentschik** [comment]
hmm, looks a bit odd. There seem to be several commits which don't belong to master. Also I get merge conflicts? Could you try to create a local feature branch based of current HV master and apply your commits on it and re-create the pull request? Or maybe we can work out together where the rebase fails?

**Comment by ctabeckey** [comment]
I agree it looked far more involved than it needed to. I'll try the local
feature branch approach. Admittedly, my GIT skills need development so
please feel free to advise.

Thanks,
Chris

**Comment by hferentschik** [comment]
>  I'll try the local feature branch approach

Cool

> my GIT skills need development so please feel free to advise.

These links might help https://help.github.com/articles/fork-a-repo/, https://help.github.com/articles/syncing-a-fork/  and https://help.github.com/articles/using-pull-requests/

Assuming _upstream_ is the name of the Hibernate Validator remote repository and you have a local clone of your forked Validator repository

    # Switch to your local master branch
    $ git checkout master 

    # Get the master from upstream, should really be a fast forward (no conflicts)
    $ git pull upstream master
    
    # Create the feature branch
    $ git checkout -b HV-872

    # Make sure all builds as expected 
    $ mvn clean install
    
    # Now the tricky part. Try merging in your changes. Looking at your original pull request https://github.com/hibernate/hibernate-validator/pull/308
    # there were only two commits, so you could try a cherry-pick and resolve all occurring merge conflicts
    $ git cherry-pick c5b6b8eb1c352a6d2b31868afcf8e1246350a633
   
    # resolve conflicts (follow merge instructions git cherry-pick will print)
    $ git cherry-pick e02da73052021bbcf143999dc73784966e9891ba

    # resolve conflicts (follow merge instructions git cherry-pick will print)

    # make sure all still builds after merging and all tests including the new one pass
    $ mvn clean install

    # Push to your fork assuming it is called _origin_
    $ git push origin HEAD

Once you have pushed to your fork you can use the Web UI to create the pull request. There are of course many other ways one could go about this, but this is the workflow I would try myself.

**Comment by emmanuelbernard** [comment]
Hi @ctabeckey, If I read the PR history correctly, you haven't tried to fix the weird commit mix, correct?
If you could that would be awesome, otherwise, we will try and find time to do it.

**Comment by gunnarmorling** [comment]
@ctabeckey, could you give some quick feedback on whether you think you still can do the rebase or not? Thanks!

**Comment by hferentschik** [comment]
superseded by #448 which now applies to master

**Pull request closed without merging**
