### PR TITLE
HV-1369 Adding def types for @Positive etc.

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://hibernate.atlassian.net/browse/HV-1369

### CODE REVIEW

**Comment by marko-bekhta** [comment]
@gunnarmorling https://hibernate.atlassian.net/browse/HV-1369 this one probably can be closed then :)

**Comment by gsmet** [comment]
@gunnarmorling yeah, I didn't do it because Marko was on it. I'll fix the issue number and merge.

**Comment by gunnarmorling** [comment]
Yeah, sorry, wasn't aware of that other issue. Was more like a one min fix.
Thanks!

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request closed without merging**
