### PR TITLE
[HV-1569] workaround gmavenplus issue to allow usage of properties ov…

### PR DESCRIPTION
**Pull request by simkam**
…erridden on command line

https://github.com/groovy/GMavenPlus/issues/72

https://hibernate.atlassian.net/browse/HV-1569

### CODE REVIEW

**Comment by gsmet** [comment]
ok to test

**Comment by gsmet** [comment]
@simkam waiting for CI to run but looks good to me.

Do you need a release with this included? I suppose you found that when testing the HV 6.0 upgrade for WildFly 12.

**Comment by simkam** [comment]
@gsmet no I don't need release right now. Yes, I started setting up TCK job.

**Comment by gsmet** [comment]
@simkam cool, thanks for the fix, I just merged it!

**Pull request merged**
