### PR TITLE
HV-1232 Making only actually set duration elements show up in error m…

### PR DESCRIPTION
**Pull request by gunnarmorling**
…essage

@gsmet @marko-bekhta Small follow-to make duration error messages a bit more concise. Could you update/provide the Ukrainian/French translations accordingly? Thanks!

Btw. I think the best would be to have a representation like "21:13:57" or "21:13:57.112000333". I.e. normalize to hours/minutes/seconds (as done by `Duration#toString`), but always show hour/minutes/seconds and optional second fractions as expressed by millis/nanos. I first tried that, but looking into `Duration#toString()` it seemed a bit more complex than anticipated, so I didn't pursue it.

### CODE REVIEW

**Comment by gsmet** [comment]
@gunnarmorling I added a commit to your PR with the French translation.

**Comment by marko-bekhta** [comment]
@gunnarmorling done.

**Comment by gunnarmorling** [comment]
Thanks, @gsmet and @marko-bekhta!

**Comment by gsmet** [comment]
Rebased and merged, thanks!

**Pull request closed without merging**
