### PR TITLE
HV-1516 Support punycode-encoded domain names

### PR DESCRIPTION
**Pull request by gsmet**
https://hibernate.atlassian.net/browse/HV-1516

@marko-bekhta can you check that it makes sense to you? Thanks!

### CODE REVIEW

**Comment by marko-bekhta** [comment]
Ha :) domain names once again. It seems we'll never stop updating the rules for them :)
I was just writing that we could simplify this by adding the dash to the `DOMAIN_CHARS_WITHOUT_DASH` and it all should work then without additional regex but then it occurred to me that there might be even easier solution to this. 
What if instead of matching a plain string we do this:
```java
		Matcher matcher = pattern.matcher( IDN.toUnicode( domain ) );
		if ( !matcher.matches() ) {
			return false;
		}
```

It will cover the cases from the issue as xn--* stuff will be converted and we would be matching the string without xn-- ?

**Comment by gsmet** [comment]
Yeah, I'm not sure it's a good idea to bet that `IDN.toUnicode()` will work on already Unicode encoded strings.

Moreover, I'm far from sure the operation is fast.

I don't think what I added is that bad.

**Comment by gsmet** [comment]
@marko-bekhta is the new version of the patch OK with you? If so, I'll merge it!

**Comment by marko-bekhta** [comment]
@gsmet looks good to me, thanks!

**Comment by gsmet** [comment]
Merged! @marko-bekhta thanks for the review.

**Pull request closed without merging**
