### PR TITLE
HV-1828 ContributorValidationMessages compatible with UTF-8 properties

### PR DESCRIPTION
**Pull request by gsmet**
https://hibernate.atlassian.net/browse/HV-1828

Supersedes https://github.com/hibernate/hibernate-validator/pull/1152 .

@jpep-in could you have a look at my changes? I think it should make things a bit better. I also fixed a couple of preexisting issues.

### CODE REVIEW

**Comment by gsmet** [comment]
@yrodiere I'm interested in a review of this one. The original issue is explained here: https://hibernate.atlassian.net/browse/HV-1828 .

**Review by yrodiere — APPROVED** [review]
LGTM, but I'd like to point out there is another aggregate bundle class, `org.hibernate.validator.resourceloading.AggregateResourceBundleLocator.AggregateBundle`, that seems to have the exact same purpose, with the same implementation.

**Review by yrodiere — APPROVED** [review]

**Comment by gsmet** [comment]
Pushed an additional commit to clean things up a bit.

@jpep-in any chance you could have a look and check things are good for you? I also prepared a 6.2 backport here if it's more practical for you: https://github.com/hibernate/hibernate-validator/pull/1155

**Comment by gsmet** [comment]
@jpep-in ping?

**Pull request merged**
