### PR TITLE
HV-955 Allowing to use constraint declaration API for configuration of default validator factory

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by hferentschik** [comment]
A integration test would be nice here as well, especially since the request comes from this corner.

**Comment by gunnarmorling** [comment]
Good idea with the integration test. Added one.

**Comment by hferentschik** [comment]
Good stuff. One of the true user value features of this sprint. Nice impl.

**Comment by hferentschik** [comment]
rebased and merged

**Pull request closed without merging**
