### PR TITLE
HV-2059 Integrate with Develocity build scans/build cache

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HV-2059

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt).
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-validator/blob/main/CONTRIBUTING.md#legal).

----------------------

### CODE REVIEW

**Review by yrodiere — CHANGES_REQUESTED** [review]
Just so we don't forget: you'll need to revert 8ff3c8b as well :)

**Comment by marko-bekhta** [comment]
something like this ? 🙈

**Review by yrodiere — APPROVED** [review]

**Comment by marko-bekhta** [comment]
thanks! 😃

**Comment by yrodiere** [comment]
Oh, you'll need this as well: https://github.com/hibernate/hibernate-search/blob/f3588e37ea76f140e823828d42487aac84f0edf4/.github/hibernate-github-bot.yml#L35-L65

**Comment by yrodiere** [comment]
FYI I updated the organization settings to give access to Develocity access keys in the GitHub Actions worflows for `hibernate/hibernate-validator`.

**Review by yrodiere — APPROVED** [review]

**Pull request merged**
