### PR TITLE
Getting rid of custom Maven mirrors

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HV-971

### CODE REVIEW

**Comment by Sanne** [comment]
@gunnarmorling the build failed because the job should be adjusted to not use the _settings-example.xml_ anymore. I can't fix that myself (and probably shouldn't until this is actually integrated)

**Comment by gunnarmorling** [comment]
Rebased and applied. Thx, @Sanne!

**Comment by gunnarmorling** [comment]
Also changed the job config. Do you have an account on CloudBees? Then I can add you to the admins if you like.

**Comment by Sanne** [comment]
I don't think I have one, np. thanks!

**Pull request merged**
