### PR TITLE
HV-887 Parameter name of an overridden method is taken from the parent c...

### PR DESCRIPTION
**Pull request by emmanuelbernard**
...lass or interface

Note that I did not follow Gunnar's proposal to favor explicit names over `argN`. We would need to propagate a flag if the `DefaultParameterNameProvider` and it's unclear it is a better and more predictable approach.

### CODE REVIEW

**Comment by hferentschik** [comment]
So what do you do to get a deterministic result?

**Comment by emmanuelbernard** [comment]
@hferentschik https://github.com/emmanuelbernard/hibernate-validator/commit/f9750a6ddf87e3fc7293d67e76c66ec30bd66333#diff-ec4255be3f0b5ad505e6f0396cfadc2cR146

I always look for the highest parent class between the various overloaded methods received.

**Comment by hferentschik** [comment]
Looking good.

> I always look for the highest parent class between the various overloaded methods received.

I prefer that as well

**Comment by hferentschik** [comment]
Merged, thanks.

**Pull request closed without merging**
