### PR TITLE
Add a ValidationSchema enum centralizing the BV schema information

### PR DESCRIPTION
**Pull request by gsmet**
**This shouldn't be committed as is**

@gunnarmorling this is what I had in mind with the enum to gather the schema information. I don't know if `ValidationSchema` is something we could move to validation-api. If we don't, we can even move the calls to the logger to `ValidationSchema.get(Configuration|Mapping)Schema` and simplify a bit more.

What I like about this is that we have all the schema information in the same place and it's easier to add a new one without touching unrelated code. And it might serve as a reference for implementors if we move it to validation-api.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Regarding moving it to _validation-api_, I'm not convinced. It seems to be an implementation detail really. In terms of simplification I'm not sure either. Seems it adds way more code lines than it removes ;) All in all I'm not sure about the problem we want to solve here I think. Happy to discuss though if you feel strongly about it.

**Comment by gsmet** [comment]
@gunnarmorling as mentioned, IMHO the main advantage is that it centralizes the information about the schemas in one and only place. No strong opinion, I just think it's nicer.

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Closing.

**Pull request closed without merging**
