### PR TITLE
fix Mod11CheckValidator for cnpj with digit check zero

### PR DESCRIPTION
**Pull request by denistiago**
pull request for this issue:  https://hibernate.atlassian.net/browse/HV-1004

### CODE REVIEW

**Comment by hferentschik** [comment]
@denistiago, could you please sign the JBoss CLA - https://cla.jboss.org/. I cannot accept your PR without a signed CLA. 

I want to cut a new release asap, so I might apply the suggested changes myself otherwise. I hope this is ok with you.

**Comment by denistiago** [comment]
@hferentschik no problem, go ahead!

**Comment by denistiago** [comment]
In the meantime i've signed the jboss cla.

**Comment by hferentschik** [comment]
> In the meantime i've signed the jboss cla.

Great. I rebased and applied your pull request

**Pull request closed without merging**
