### PR TITLE
HV-1887 Make Java 11 the base Java version

### PR DESCRIPTION
**Pull request by gsmet**
In passing, remove the Jakarta staging repository.

https://hibernate.atlassian.net/browse/HV-1887

### CODE REVIEW

**Comment by scottmarlow** [comment]
@gsmet does it help to use the `1.6` signature tool?
```
  <version.sigtest.plugin>1.6</version.sigtest.plugin>
```

**Comment by gsmet** [comment]
Not really. I tried with it and then moved to 2.0-SNAPSHOT to be able to exclude the JDK classes and then things got worse :).

**Comment by starksm64** [comment]
The 1.6 sigtest plugin was what I was testing with in my branch, and that was working:
```
└> mvn -pl tck-runner clean install -DskipTests -Psigtest
...
[INFO] --- sigtest-maven-plugin:1.6:check (default) @ hibernate-validator-tck-runner ---
[INFO] Packages: jakarta.validation,jakarta.validation.bootstrap,jakarta.validation.constraints,
                                jakarta.validation.constraintvalidation,jakarta.validation.executable,jakarta.validation.groups,
                                jakarta.validation.metadata,jakarta.validation.spi,jakarta.validation.valueextraction
[INFO] SignatureTest report
Base version: 3.0.0
Tested version: 7.0.3-SNAPSHOT
Check mode: src [throws normalized]
Constant checking: on



[INFO] /Users/starksm/Dev/JBoss/Jakarta/rh-hv/tck-runner/target/surefire-reports/sigtest/TEST-hibernate-validator-tck-runner-7.0.3-SNAPSHOT.xml: 0 failures in /Users/starksm/Dev/JBoss/Jakarta/rh-hv/tck-runner/target/api-signature/validation-api-java8.sig
```

I'm using Java 11:
└> $JAVA_HOME/bin/java -version
java version "11.0.13" 2021-10-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.13+10-LTS-370)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.13+10-LTS-370, mixed mode)

**Comment by starksm64** [comment]
I also just pulled down the latest upstream HV and see that is it using Java 17 to build. I did that, and ran the sig tests and those are also working:
```
✏️ [starksm@Scotts-iMacPro#10433]-(hibernate-validator)-[git://main ✔]-
└> git remote -v
origin  https://github.com/hibernate/hibernate-validator.git (fetch)
origin  https://github.com/hibernate/hibernate-validator.git (push)
✏️ [starksm@Scotts-iMacPro#10434]-(hibernate-validator)-[git://main ✔]-
└> $JAVA_HOME/bin/java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
...
✏️ [starksm@Scotts-iMacPro#10435]-(hibernate-validator)-[git://main ✔]-
└> mvn -pl tck-runner clean install -DskipTests -Psigtest
...
[INFO] --- sigtest-maven-plugin:1.4:check (default) @ hibernate-validator-tck-runner ---
[INFO] Packages: jakarta.validation,jakarta.validation.bootstrap,jakarta.validation.constraints,
                                jakarta.validation.constraintvalidation,jakarta.validation.executable,jakarta.validation.groups,
                                jakarta.validation.metadata,jakarta.validation.spi,jakarta.validation.valueextraction
[INFO] SignatureTest report
Base version: 3.0.0
Tested version: 8.0.0-SNAPSHOT
Check mode: src [throws normalized]
Constant checking: on



[INFO] /Users/starksm/Dev/JBoss/Jakarta/hibernate-validator/tck-runner/target/surefire-reports/sigtest/TEST-hibernate-validator-tck-runner-8.0.0-SNAPSHOT.xml: 0 failures in /Users/starksm/Dev/JBoss/Jakarta/hibernate-validator/tck-runner/target/api-signature/validation-api-java8.sig
[INFO] 
```

**Comment by starksm64** [comment]
Ok, let me take a look at this branch. @scottmarlow and I will try to figure the easiest thing to do.

**Comment by scottmarlow** [comment]
Do we need to add a `signature-generation` profile[ like the CDI-TCK](https://github.com/eclipse-ee4j/cdi-tck/blob/master/impl/pom.xml#L351)?

**Comment by gsmet** [comment]
That's a good idea. I'll have a look tomorrow morning and see if I can make that work.

**Comment by starksm64** [comment]
The following works for me:
In addition to updating the java-version.main.release to 11 and building with 17, update the version.sigtest.plugin to 2.0-SNAPSHOT and build the latest https://github.com/jtulach/netbeans-apitest.git with JDK 17 and update the sigtest plugin config to:

```
                <plugin>
                    <groupId>org.netbeans.tools</groupId>
                    <artifactId>sigtest-maven-plugin</artifactId>
                    <version>${version.sigtest.plugin}</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <ignoreJDKClasses>
                            <include>java.lang.Deprecated</include>
                            <include>java.lang.Object</include>
                        </ignoreJDKClasses>
                    </configuration>
                </plugin>
```

This allows the sigtest verification to work with the current jdk8 version of the signature map file:
```
└> mvn -pl tck-runner clean install -DskipTests -Psigtest
...
[INFO] --- sigtest-maven-plugin:2.0-SNAPSHOT:check (default) @ hibernate-validator-tck-runner ---
[INFO] Packages: jakarta.validation,jakarta.validation.bootstrap,jakarta.validation.constraints,
                                jakarta.validation.constraintvalidation,jakarta.validation.executable,jakarta.validation.groups,
                                jakarta.validation.metadata,jakarta.validation.spi,jakarta.validation.valueextraction
[INFO] SignatureTest report
Base version: 3.0.0
Tested version: 8.0.0-SNAPSHOT
Check mode: src [throws normalized]
Constant checking: on



[INFO] /Users/starksm/Dev/JBoss/Jakarta/hibernate-validator/tck-runner/target/surefire-reports/sigtest/TEST-hibernate-validator-tck-runner-8.0.0-SNAPSHOT.xml: 0 failures in /Users/starksm/Dev/JBoss/Jakarta/hibernate-validator/tck-runner/target/api-signature/validation-api-java8.sig
[INFO] 
```

The changes are in:
[hv.patch.txt](https://github.com/hibernate/hibernate-validator/files/8158771/hv.patch.txt)


If you want a validation-api-java11.sig created I can do that in a 3.0.2 service release.

**Comment by gsmet** [comment]
I went with @scottmarlow 's proposal and generated a signature file locally with Java 11.

@starksm64 
It would be nice if we could have a Java 11 signature IN ADDITION TO the current Java 8 sig file in the TCK.
Not sure if it's worth doing it though given we will have to change the build infra.
Currently we enforce Java 8 for the build, we could probably switch to Java 11 and keep a 8 bytecode compatibility though (we need to keep Java 8 compatibility as we keep the major version as is) if it's not too much hassle on the Eclipse infra build.

Let me know if you think we should move to Java 11 for the TCK build, I can do the grunt work.

**Comment by scottmarlow** [comment]
@gsmet do we also pass the signature tests against Java 17?

**Comment by gsmet** [comment]
We only do it for the base version so until now Java 8 and for HV 8, Java 11 (that's how it was always done).

**Comment by scottmarlow** [comment]
Looking forward, it would be good if we could support https://jakarta.ee/specifications/platform/9.1/jakarta-platform-spec-9.1.html#container-requirements (https://github.com/eclipse-ee4j/jakartaee-platform/pull/302):
```
2.4.1. Container Requirements

This specification requires that containers support execution in a Java™ runtime environment, as defined by the Java Platform, Standard Edition specification, v8 or later (Java SE 8 or later).
```
Support for running against Java SE 8+ JDKs ^ came into the sigtest tooling via https://github.com/jtulach/netbeans-apitest/pull/2 + https://github.com/jtulach/netbeans-apitest/pull/8 + https://github.com/jtulach/netbeans-apitest/pull/11 explains and introduces the `ignoreJDKClasses` option so that you can run against a base SE version or later versions.  IMO, it is a hacky option but it seems to help so far with Jakarta EE 9.1+.  The original need was described in https://github.com/eclipse-ee4j/jakartaee-tck/issues/156 in case that helps for more background info.

**Comment by gsmet** [comment]
Not sure what you're saying exactly? Are you saying we should still support Java 8 in HV 8 targeting EE 10?

Because the new EL impl, Expressly, does not support Java 8 AFAICS. That's one of the reasons why I moved to Java 11.

**Comment by scottmarlow** [comment]
> Not sure what you're saying exactly? Are you saying we should still support Java 8 in HV 8 targeting EE 10?

For EE 10, we would only target Java 11+ (with the JDK 11 signature file) which could include running signature tests (with ignoreJDKClasses specified)  against later Java SE versions as well.  

> 
> Because the new EL impl, Expressly, does not support Java 8 AFAICS. That's one of the reasons why I moved to Java 11.

**Pull request merged**
