### PR TITLE
HV-2015 Use Jakarta EE 11 BOM 

### PR DESCRIPTION
**Pull request by marko-bekhta**
https://hibernate.atlassian.net/browse/HV-2015
https://hibernate.atlassian.net/browse/HV-2001

I'll open this one as a draft only, to see if it works ok on CI as well.

this passed locally, but I guess to make it all actually pass and use the Jakarta EE 11 specs, those have to be available in WildFly. I suppose we could try patching some of the modules, but that's probably going to be a pain. 

Also bumped the expressly version to 6, but since it is only available in the Jakarta staging repository ... I guess we would need to wait with a final release of HV until there's a version of expressly available in the maven central 😕   

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt).
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-validator/blob/main/CONTRIBUTING.md#legal).

----------------------

### CODE REVIEW

**Comment by gsmet** [comment]
I’m on my phone but their BOM looks a bit odd with some exclusions. I’m not really sure it’s a good idea to use it.

**Comment by marko-bekhta** [comment]
Yeah, maybe... I was looking for something where it is clear what's in EE11 and which specification version to use... browsing through spec list wasn't too helpful 🥲. Some specs referenced in HV build seems to not have a 11 variant, but then I found them in this BOM... so this definitely would need some more thinking 😃 before it goes out of draft 😃

**Comment by marko-bekhta** [comment]
> their BOM looks a bit odd with some exclusions

I looked at `jakarta.enterprise.cdi-api` as an example, and from what I can see, CDI API depends, among other libs, on `jakarta.inject-api`. With that exclusion in BOM, it forces us to add `jakarta.inject-api` explicitly if our code is using `@Inject` which I guess makes sense (we shouldn't include things that come from transitive dependencies directly in our code).
That BOM only manages `jakarta.*` dependencies, which is nice 😄. 
So maybe it's not that terrible to use that BOM after all... 

Now, how do we think we should move forward? I'm thinking:
- bump Jakarta specs, either with this BOM, or manually, but to versions from this BOM,
- since WildFly is not including EE11 specs yet and the build with bumped versions passed, keep things as is and wait for WildFly, i.e. do not add more patching to the HV build to adjust WF for these newer specs ... 
- ping someone on Expressly to ask them for a release to Central
  * if we can get an Expressly release compatible with EL 6, then it's all ok. This way, we can try releasing HV 9 Beta (as planned before)
  * if we cannot get an Expressly release, keep it (and EL API) at 5. This way, we do an Alpha release and mention that EL/Expressly will be updated before we get to the Beta/CR

@gsmet @yrodiere WDYT?

**Comment by yrodiere** [comment]
> I looked at jakarta.enterprise.cdi-api as an example, and from what I can see, CDI API depends, among other libs, on jakarta.inject-api. With that exclusion in BOM, it forces us to add jakarta.inject-api explicitly if our code is using @Inject which I guess makes sense (we shouldn't include things that come from transitive dependencies directly in our code).

Wouldn't go as far as saying it makes sense, but it *is* the way things are usually done in the Jakarta EE world -- or at least, in the WildFly world. I'm honestly more surprised exclusions are not done consistently in this BOM -- some dependencies have no exclusions.

These exclusions drive me mad, but they're very common and have reasons to be. The idea is that (as you said) your code should declare explicitly all its dependencies, and _implementations_ of your dependencies will take care of pulling in all necessary transitive dependencies. As you know, in the app server world, implementations aren't necessarily known at compile time.

>  So maybe it's not that terrible to use that BOM after all...

I think it's tolerable, *if* you are sure the BOM won't arbitrarily remove some transitive dependencies and cause Java SE applications to miss them. I.e. your tests' dependencies need to be extra clean, so that test dependencies don't offset problems in the main dependencies. 

> since WildFly is not including EE11 specs yet and the build with bumped versions passed, keep things as is and wait for WildFly, i.e. do not add more patching to the HV build to adjust WF for these newer specs ...

Getting WildFly to work is definitely a second step. Let's release a Beta first.

> ping someone on Expressly to ask them for a release to Central 

+1 this is very odd, let's get some more information.

> @gsmet @yrodiere WDYT?

My main concern is about the timeline. We can't have non-final dependencies in HV, and the Jakarta EE 11 BOM is tagged "M4", so I guess non-final.
Are you sure we can wait until the Jakarta EE 11 BOM gets released before we release HV 9.0.0.Final?
Or maybe that's a moot point because POM flattening hides the Jakarta EE 11 BOM anyway?

**Comment by marko-bekhta** [comment]
> +1 this is very odd, let's get some more information.

I've created a GH issue, and Arjan replied that he'll push it to Central, so I'll keep an eye on it. But to your point:

> We can't have non-final dependencies in HV

it would still mean that HV is relying on an M1 dependency, even though EL is an optional dependency and HV can work without it, but then it means that HV is missing one of the spec features: https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#non-el-message-interpolator

I think that from the HV standpoint, it needs Jakarta Validation, CDI, and EL specs; it mentions the persistence spec as well, but it is the persistence spec that integrates the BV, so we may not care about it as a dependency from a spec perspective, but we do have some HV features based on it (`JPATraversableResolver`) so we do need it too. 

> Or maybe that's a moot point because POM flattening hides the Jakarta EE 11 BOM anyway?

This is also true; the published poms are flattened, so we don't really include that BOM in what we publish.

**Comment by yrodiere** [comment]
> it would still mean that HV is relying on an M1 dependency

Expressly not being Final is IMO a blocker for a Final release of HV. We can still release an Alpha/Beta, but as long as our dependencies are not Final, we're stuck.

FWIW even if we made an exception just this once, I'm pretty sure the (transitive) dependency to a non-final version would be a blocker for integration into WildFly or Quarkus.

**Comment by gsmet** [comment]
Are you flattening the pom file? If  not, I think it would be worth checking this patch doesn't cause any problem downstream.
It could be done in Quarkus with a draft PR once you have a Beta1 one out.

**Comment by gsmet** [comment]
(And TBH, I wonder if it would make sense to flatten the POM files for the Hibernate libraries)

**Comment by marko-bekhta** [comment]
hey 😃,
Yes the poms a flattend. Here's an example of the engine POM based on this PR:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Hibernate Validator, declare and validate application constraints
  ~
  ~ License: Apache License, Version 2.0
  ~ See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.
  -->
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.hibernate.validator</groupId>
  <artifactId>hibernate-validator</artifactId>
  <version>9.0.0-SNAPSHOT</version>
  <name>Hibernate Validator Engine</name>
  <description>Hibernate's Jakarta Validation reference implementation.</description>
  <url>http://hibernate.org/validator/hibernate-validator-public-parent/hibernate-validator</url>
  <licenses>
    <license>
      <name>Apache License 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>epbernard</id>
      <name>Emmanuel Bernard</name>
      <email>emmanuel@hibernate.org</email>
      <url>http://in.relation.to/emmanuel-bernard/</url>
      <organization>Red Hat, Inc.</organization>
    </developer>
    <developer>
      <id>hardy.ferentschik</id>
      <name>Hardy Ferentschik</name>
      <email>hferents@redhat.com</email>
      <url>http://in.relation.to/hardy-ferentschik/</url>
      <organization>Red Hat, Inc.</organization>
    </developer>
    <developer>
      <id>gunnar.morling</id>
      <name>Gunnar Morling</name>
      <email>gunnar@hibernate.org</email>
      <url>http://in.relation.to/gunnar-morling/</url>
      <organization>Red Hat, Inc.</organization>
    </developer>
    <developer>
      <id>kevinpollet</id>
      <name>Kevin Pollet</name>
      <email>kevin.pollet@serli.com</email>
      <url>http://www.serli.com/</url>
      <organization>SERLI</organization>
    </developer>
    <developer>
      <id>davide.dalto</id>
      <name>Davide D'Alto</name>
      <email>davide@hibernate.org</email>
      <url>http://in.relation.to/davide-dalto/</url>
      <organization>Red Hat, Inc.</organization>
    </developer>
    <developer>
      <id>guillaume.smet</id>
      <name>Guillaume Smet</name>
      <email>guillaume.smet@hibernate.org</email>
      <url>http://in.relation.to/guillaume-smet/</url>
      <organization>Red Hat, Inc.</organization>
    </developer>
    <developer>
      <id>marko.bekhta</id>
      <name>Marko Bekhta</name>
      <email>marko.prykladna@gmail.com</email>
      <url>http://in.relation.to/marko-bekhta/</url>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:git://github.com/hibernate/hibernate-validator.git/hibernate-validator-public-parent/hibernate-validator</connection>
    <developerConnection>scm:git:git@github.com:hibernate/hibernate-validator.git/hibernate-validator-public-parent/hibernate-validator</developerConnection>
    <url>http://github.com/hibernate/hibernate-validator/hibernate-validator-public-parent/hibernate-validator</url>
  </scm>
  <dependencies>
    <dependency>
      <groupId>jakarta.validation</groupId>
      <artifactId>jakarta.validation-api</artifactId>
      <version>3.1.0</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <groupId>*</groupId>
          <artifactId>*</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging</artifactId>
      <version>3.6.0.Final</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.fasterxml</groupId>
      <artifactId>classmate</artifactId>
      <version>1.7.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.glassfish.expressly</groupId>
      <artifactId>expressly</artifactId>
      <version>6.0.0-M1</version>
      <scope>provided</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.jboss.logging</groupId>
      <artifactId>jboss-logging-annotations</artifactId>
      <version>3.0.1.Final</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <version>3.2.0</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>2.12.7</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.thoughtworks.paranamer</groupId>
      <artifactId>paranamer</artifactId>
      <version>2.8</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>javax.money</groupId>
      <artifactId>money-api</artifactId>
      <version>1.1</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.openjfx</groupId>
      <artifactId>javafx-base</artifactId>
      <version>17.0.12</version>
      <scope>compile</scope>
      <optional>true</optional>
    </dependency>
  </dependencies>
</project>
```
And we do the same for Search.

**Comment by yrodiere** [comment]
> ```
>     <developer>
>       <id>marko.bekhta</id>
>       <name>Marko Bekhta</name>
>       <email>marko.prykladna@gmail.com</email>
>       <url>http://in.relation.to/marko-bekhta/</url>
>     </developer>
> ```

Missing a `      <organization>Red Hat, Inc.</organization>` here :P

**Comment by marko-bekhta** [comment]
> Missing a       <organization>Red Hat, Inc.</organization> here :P

Who's that guy anyway? 🤔 😅 😆

**Comment by marko-bekhta** [comment]
I was looking at all the poms to make sure they look fine. And that made me thinking. Currently in engine we have a
```xml
        <dependency>
            <groupId>org.glassfish.expressly</groupId>
            <artifactId>expressly</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
```

I'd assume that we really need only a dependency on the EL API, and let the user pick the implementation....
But ... there are these lines:

https://github.com/hibernate/hibernate-validator/blob/33d821c6fd25112ff1eee4a448058b2c251180cf/engine/src/main/java/org/hibernate/validator/messageinterpolation/ResourceBundleMessageInterpolator.java#L198-L205

Where an impl class is used to get a CL to make things work in OSGi... so we can't remove the dependency without removing this block of code ... 
- do we care about OSGi ?
- maybe there's a different way to get a correct CL? 
- don't bother and leave things as they are 😃

**Comment by marko-bekhta** [comment]
OK I couldn't see any obvious issues with the flattened pom/module info files, let's merge this one 🤞🏻
Thank you all for taking a look 🏆

**Comment by marko-bekhta** [comment]
Just created https://hibernate.atlassian.net/browse/HV-2020 to "track" this  😃 

> I'd say it's acceptable to just drop OSGi support in HV 9.

I guess it already is not tested 🙈, we have  the OSGi directory, but it has been excluded from the build https://github.com/hibernate/hibernate-validator/commit/7b7e6799760b9df7f6a93a19ccbfcac92629ce8b
And from what I can see 7.0 was the last version which published something OSGi related: https://repo1.maven.org/maven2/org/hibernate/validator/hibernate-validator-osgi-karaf-features/

**Comment by yrodiere** [comment]
> Just created https://hibernate.atlassian.net/browse/HV-2020 to "track" this 😃
> 
> > I'd say it's acceptable to just drop OSGi support in HV 9.
> 
> I guess it already is not tested 🙈, we have the OSGi directory, but it has been excluded from the build [7b7e679](https://github.com/hibernate/hibernate-validator/commit/7b7e6799760b9df7f6a93a19ccbfcac92629ce8b) And from what I can see 7.0 was the last version which published something OSGi related: https://repo1.maven.org/maven2/org/hibernate/validator/hibernate-validator-osgi-karaf-features/

I hear you say "someone needs to update OSGi tests" and I can only answer "not me".

If we're already not testing, and not publishing OSGi features, and nobody's been complaining, IMO it's time to create an issue to drop OSGi support, go through code and documentation to remove any reference, and add an entry to the migration guide.

**Pull request merged**
