### PR TITLE
HV-862 ExecutableHelper#overrides() should take visibilities into acc…

### PR DESCRIPTION
**Pull request by DavideD**
…ount

  This is already working. The commit adds a test.

https://hibernate.atlassian.net/browse/HV-862

### CODE REVIEW

**Comment by DavideD** [comment]
Is there some other use case to consider?

**Comment by gunnarmorling** [comment]
No, I think that's the one.

**Comment by gunnarmorling** [comment]
Thinking about it, one edge case remains: A super-type declaring a package-private method (default visibility), and a sub-type in another package specifies a method with the identical signature. This is no method overriding, but I suppose the current code would not handle this correctly.

**Comment by DavideD** [comment]
I'll have a look

**Comment by DavideD** [comment]
I added a commit to test the package-private use case

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks, @DavideD!

**Pull request closed without merging**
