### PR TITLE
HV-1705 Upgrade WildFly to 16.0.0.Final

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by Sanne** [comment]
merged in master. I'll run a local build on the backport before pushing that...

**Comment by gsmet** [comment]
@Sanne already done for the backport :)

**Comment by gsmet** [comment]
Thanks for merging.

**Comment by Sanne** [comment]
ok, it's taking a while to download wf16...  I'll let you mark the JIRA resolved then? thanks

**Pull request merged**
