### PR TITLE
HV-1064 Add Travis support

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by hferentschik** [comment]
I added a comment to HV-1064 itself. I am kind of wondering what we gain here.

**Comment by gunnarmorling** [comment]
Anything missing from this? I think it's good to go, right?

**Comment by hferentschik** [comment]
I think we wanted to add some more info into the README

**Comment by gsmet** [comment]
I added something along the lines of what we discussed to the README.md.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks, @gsmet!

**Pull request closed without merging**
