### PR TITLE
HV-1104 Upgrade Karaf to 4.0.7 in our OSGi integration test

### PR DESCRIPTION
**Pull request by gsmet**
- https://hibernate.atlassian.net/browse/HV-1104

Minor but I want to see if it helps mitigate our CI issues.

### CODE REVIEW

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
@gunnarmorling it does not solve the test issue but I think we should commit this anyway as we will need to upgrade Karaf in the future for JDK 9 support (see the tests made by Freeman Fang in https://hibernate.atlassian.net/browse/HV-1051) and we need to fix the prerequisite thing to make it work.

**Comment by gunnarmorling** [comment]
Hum, this one gives me a JVM crash when running the OSGi tests:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project hibernate-validator-osgi-integrationtest: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?

**Comment by gsmet** [comment]
Maybe it triggers the same bug we have on CI? Did you try with a more recent JVM?

**Comment by gunnarmorling** [comment]
@gsmet Tried with JDK 1.8b101, same exception.

**Comment by gsmet** [comment]
This is very bad news indeed.

**Comment by gsmet** [comment]
@gunnarmorling could you share the error file dumped by the JVM?

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gunnarmorling** [comment]
> @gunnarmorling could you share the error file dumped by the JVM?

@gsmet Where would I find that file or what options would I need to create this file?

**Comment by gsmet** [comment]
@gunnarmorling last time my JVM got killed like that, I had an error file in my workspace. If it did create it, a `git status` should point it to you.

**Comment by gsmet** [comment]
@gunnarmorling the file is named hs_err_pidXXXX.log (with XXXX, the pid number)

**Comment by gsmet** [comment]
@gunnarmorling the file is named hs_err_pidXXXX.log (with XXXX, the pid number)

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gunnarmorling** [comment]
Hi @gsmet, so downgrading to Surefire 2.18.1 as you suggested makes things work indeed. Any idea what's the issue in 2.19? I'd add a commit for this and merge this PR then. Note that I'm still seeing this slowdown in OSGi tests (it seems to wait for a 30 sec timeout), but it still passes. It's not so nice but still better than getting this exception.

**Comment by gunnarmorling** [comment]
Hi @gsmet, what should we do with this one? Seems the problems on CI are fixed now, also without it? If so, I'd prefer to not merge it as it gives me that 30 sec penalty in the build.

**Comment by gsmet** [comment]
@gunnarmorling We can either merge it as a first step or we can wait a version compatible with JDK9 before upgrading. I think it would be better to upgrade but I'm still concerned about your timeout issue. It would be a good idea to `kill -3` the process to understand what's going on.

**Comment by gsmet** [comment]
@gunnarmorling any news on the `kill -3` front?

**Comment by gsmet** [comment]
I upgraded to 4.0.7. Interested to see if you can reproduce your issue and get a `kill -3` output of the stalled process if so. I would like us to be ready when Karaf releases a JDK9 ready version.

**Comment by gunnarmorling** [comment]
Rebased, applied and added one more commit to address that annoying timeout issue. The problem was that Karaf 4.0.4 and beyond [pull in](http://repo1.maven.org/maven2/org/apache/karaf/features/standard/4.0.4/standard-4.0.4-features.xml) the "management" feature with the "standard" feature we had enabled as boot feature in the test. This causes problems with firewalls potentially which prevent the exposure of the JMX server. Changed it to only use "system" now which seems enough for our purposes. If needed, we can re-add further features from the "standard" or "minimum" feature later on.

**Pull request closed without merging**
