### PR TITLE
HV-1252 Adding a unit test

### PR DESCRIPTION
**Pull request by ghusta**
I've added a unit test for the bug HV-1252.

It permits to see there are compilation errors with @Currency and MonetaryAmount badly reported.

https://hibernate.atlassian.net/browse/HV-1252

### CODE REVIEW

**Comment by gunnarmorling** [comment]
OK to test

**Comment by gsmet** [comment]
@ghusta can you sign the CLA for the Hibernate Validator project on https://cla.jboss.org/index.seam and ping me here with your username once done?

Thanks!

**Comment by gsmet** [comment]
@ghusta btw, from your comments on JIRA, it looks like you're not far from a fix. Wanna give it a try? If not, I'll fix it.

**Comment by gsmet** [comment]
@ghusta Hi! Did you see my message about the CLA (https://github.com/hibernate/hibernate-validator/pull/676#issuecomment-280707413)? We need it to incorporate your code into the code base.

Thanks for your feedback.

**Comment by ghusta** [comment]
Hello. I was offline for a while, but I'm back now ;-)
I'll try to have a look at this today, and fix the bug if I can.
Thanks

**Comment by ghusta** [comment]
@gsmet : BTW I signed the CLA, my username is ghusta.

**Comment by gsmet** [comment]
@ghusta I squashed all your commits in one and added an additional commit to make things more consistent (they weren't before your patch so it's more a general clean up).

Note that if you plan to contribute further, we generally work on the master branch and then backport the fixes to the 5.4 branch. I did the work to apply your patch to master.

Thanks for your contribution!

**Comment by ghusta** [comment]
OK very well. I think I had some problems while rebasing... 
It will be clearer like that. It's never perfect the first time ;-)
Thank you.

**Comment by ghusta** [comment]
BTW did you format the code (code style) with IntelliJ or with Eclipse ?
I did it with IntelliJ and didn't have the same result than with your clean up

**Comment by marko-bekhta** [comment]
@ghusta it's a custom formatting for both IDEs. If you'd like to get a style files please check here - https://github.com/hibernate/hibernate-ide-codestyles

**Comment by gsmet** [comment]
@ghusta yeah, as the code was not very consistent earlier, it's not always easy to choose how to format your code, that's why I made it consistent.

I use Eclipse. I know @marko-bekhta uses Intellij and he contributed updates to our code styles configuration but I'm not sure they are perfect: https://github.com/hibernate/hibernate-ide-codestyles . Not really easy to configure different IDEs to get the exact same formatting output.

BTW, do you need a release soon or it was just to experiment and you can use the snapshots? If you need something soon, we can plan a 5.4.1 release next week.

**Comment by ghusta** [comment]
@gsmet OK it's the code style I imported for the project (hibernate-ide-codestyles).
Maybe next time I'll use this plugin : [Eclipse Code Formatter for IntelliJ IDEA](https://plugins.jetbrains.com/idea/plugin/6546-eclipse-code-formatter).

Concerning the bug, I was just experimenting with 5.4. I'm not in a hurry !

**Pull request closed without merging**
