### PR TITLE
HV-1645 Mitigate CDI startup time regression due to ValidateableBeanFilter

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/HV-1645

This is the master patch. Branch for 6.0: https://github.com/gsmet/hibernate-validator/tree/cdi-performance-issue-6.0 .

@aguibert let's discuss this issue here.

### CODE REVIEW

**Comment by gsmet** [comment]
@marko-bekhta interested in your thoughts on this one.

**Comment by gsmet** [comment]
Closing this one in favor of a full revert: https://github.com/hibernate/hibernate-validator/pull/981 .

**Comment by aguibert** [comment]
Hi @gsmet, I agree that a full revert would be a better option here.  Much appreciated!

**Comment by gsmet** [comment]
@aguibert not yet announced but I released HV 6.0.12.Final on Friday, reverting the whole thing. Announce to come soon.

Note that you will need the BV TCK 2.0.4.Final. I notified Oracle about the BV TCK update.

**Pull request closed without merging**
