### PR TITLE
HV-1244 Add translation of ValidationMessages for Persian language

### PR DESCRIPTION
**Pull request by shahramgdz**
Support Persian(fa) language

### CODE REVIEW

**Comment by gsmet** [comment]
ok to test

**Comment by gunnarmorling** [comment]
Thanks, @shahramgdz! Can you please sign the JBoss contributor license agreement? It's a web app living at https://cla.jboss.org/. It's needed in order to merge your PR. Thanks!

**Comment by shahramgdz** [comment]
@gunnarmorling, done.

**Comment by gsmet** [comment]
@shahramgdz merged, thanks!

While you're at it, could you take a look at the new strings we added at the bottom of the file for duration validation? See https://github.com/hibernate/hibernate-validator/blob/master/engine/src/main/resources/org/hibernate/validator/ValidationMessages.properties .

**Pull request closed without merging**
