### PR TITLE
HV-1708 Create ValidationMessages_da.properties

### PR DESCRIPTION
**Pull request by preuss**
HV-1708 Add danish validation to ValidationMessages.properties

### CODE REVIEW

**Comment by yrodiere** [comment]
Jenkins, retest this please.

**Comment by gsmet** [comment]
@preuss looks good to me, thanks!

Would you mind adding your real name in `copyright.txt`? The names are sorted in alphabetical order of first name. If you prefer not to, no worries, I just thought you might want to.

**Comment by preuss** [comment]
@gsmet I have added it to my branch, should I make a new pull request.

**Comment by gsmet** [comment]
Found your name in the original JIRA so I updated `copyright.txt`.

Merged, thanks!

**Comment by gsmet** [comment]
@preuss no worries, I beat you to it!

**Pull request closed without merging**
