### PR TITLE
Incorrect Pax URL syntax for paranamer

### PR DESCRIPTION
**Pull request by tonit**
Incorrect Pax URL syntax for bundle (dependency) com.thoughtworks.paranamer/paranamer

### CODE REVIEW

**Comment by gsmet** [comment]
@tonit Hi!

Thanks for your PR. Could you take the time to add a test in our OsgiIntegrationTest? It's apparently missing :).

And could you please sign the CLA for the Hibernate Validator project here: https://cla.jboss.org/ ?

Thanks!

**Comment by tonit** [comment]
I have just added tests for this. CLA will come..

**Comment by tonit** [comment]
CLA signed. (tonitcom)

**Comment by gsmet** [comment]
@tonit thanks! I amended the commit messages to include a JIRA issue number and made a few very minor improvements.

Merged to master and the 5.4 branch.

**Pull request closed without merging**
