### PR TITLE
HV-1775 Rename CDI extension service file for new jakarta package

### PR DESCRIPTION
**Pull request by jGauravGupta**
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

### CODE REVIEW

**Comment by gsmet** [comment]
ok to test

**Comment by gsmet** [comment]
@jGauravGupta thanks! Unfortunately, I wasn't able to test the CDI extension back in the time because I had no CDI implementation available.

I amended your commit to include a JIRA issue number.

Do you have more fixes coming or should I release an Alpha2?

**Comment by gsmet** [comment]
OK, I was able to restore the CDI extension tests as Weld has made progress on their side.

Following your PR, all the tests pass so I'm releasing 7.0.0.Alpha2. It should synced to Central sometime tomorrow.

**Comment by gsmet** [comment]
@jGauravGupta Alpha2 is now available on Central.

**Comment by jGauravGupta** [comment]
Thanks @gsmet

**Pull request merged**
