### PR TITLE
HV-1013 Avoiding call of hashCode() of validated objects in caching t…

### PR DESCRIPTION
**Pull request by gunnarmorling**
…raversable resolver

@hferentschik You may be interested. Actually it's doing the same now as `ValidationContext.BeanAndPath`.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
This one should be merged into 5.3, too.

**Comment by gsmet** [comment]
Mmmh, there are 2 different changes here.

I agree with the first one (the System.identityHashCode change).

But I'm not sure I follow you on the second one. Are you sure using just the object and the property node as key for the cache is sufficient? It makes me a little nervous for 2 reasons:
- the values cached (reachable and cascadable) depend on all the other parameters as we call the methods with all the parameters,
- I would have expected the full property path to be meaningful and the leaf property node does not look sufficient to me.

**Comment by gunnarmorling** [comment]
About your concern, I see where you are coming from.

I can't see a case really where the outcome for the same object and property would be different, so I believe the other params are passed as some means of context (either a given reference is loaded or not, no matter the element type of the association or what's the root of the current traversal). But I'll revert that part of the change to be on the safe side.

**Comment by gunnarmorling** [comment]
@gsmet Force pushed an update.

**Comment by gsmet** [comment]
Merged! Thanks!

**Comment by gsmet** [comment]
And cherry-picked to 5.3.

**Comment by fcamblor** [comment]
I'm still getting an error (but with different stacktrace) after an upgrade to `5.4.1.Final` :
```
	foo.bar.web.assets.AssetsController$DynamicSVGParams.hashCode(AssetsController.java:134)
	org.hibernate.validator.internal.engine.ConstraintViolationImpl.createHashCode(ConstraintViolationImpl.java:328)
	org.hibernate.validator.internal.engine.ConstraintViolationImpl.<init>(ConstraintViolationImpl.java:165)
	org.hibernate.validator.internal.engine.ConstraintViolationImpl.forBeanValidation(ConstraintViolationImpl.java:56)
	org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolation(ValidationContext.java:344)
	org.hibernate.validator.internal.engine.ValidationContext.createConstraintViolations(ValidationContext.java:260)
	org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:454)
	org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:127)
	org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:87)
	org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:73)
	org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:616)
	org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:581)
	org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:527)
	org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:495)
	org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:460)
	org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:410)
	org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:207)
	org.springframework.validation.beanvalidation.SpringValidatorAdapter.validate(SpringValidatorAdapter.java:253)
```

My `DynamicSVGParams` class looks like this :
```
    public static class DynamicSVGParams {
        @NotNull
        String path;
        @NotNull
        String color;

        @AssertTrue
        @JsonIgnore
        public boolean isSvgPathValid() {
            // That's an important security constraint, otherwise, we're going to be able to serve any file in the WEB-INF
            // folder (like configuration files for instance...)
            return path.endsWith(".svg");
        }

        @AssertTrue
        @JsonIgnore
        public boolean isSvgColorValid() {
            return Colors.isValidHexColor(color);
        }

        public String getPath() {
            return path;
        }

        public void setPath(String path) {
            this.path = path;
        }

        public String getColor() {
            return color;
        }

        public void setColor(String color) {
            this.color = color;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            DynamicSVGParams that = (DynamicSVGParams) o;

            if (!path.equals(that.path)) return false;
            return color.equals(that.color);

        }

        @Override
        public int hashCode() {
            int result = path.hashCode();
            result = 31 * result + color.hashCode();
            return result;
        }
    }
```

**Comment by gsmet** [comment]
It is a different issue: https://hibernate.atlassian.net/browse/HV-1373 .

It has been fixed in 6.0.4.Final. Could you consider an upgrade to the latest 6.0.x? We are at 6.0.16.Final right now.

**Comment by fcamblor** [comment]
Wow thanks for the quick response and the pointer (I tried some search but didn't found it, sorry for the useless noise)

Will try to upgrade to BV 2.0 and HV 6.x thanks :-)

**Pull request closed without merging**
