### PR TITLE
HV-1184 add synthetic check to ConstraintDescriptorImpl.buildAnnotationParameterMap

### PR DESCRIPTION
**Pull request by jmax01**
[HV-1184](https://hibernate.atlassian.net/browse/HV-1184) add synthetic check to ConstraintDescriptorImpl.buildAnnotationParameterMap

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hi, out of curiosity, which test was giving you that error? Are you planning add the actual JaCoCo config, too? I think it'd make sense to do this together, as otherwise the change in `ConstraintDescriptorImpl` isn't really needed.

Could you also sign the JBoss contributor license agreement? It's a small web app living at http://cla.jboss.org/. We'll need that in order to merge your changes. Thanks!

**Comment by gsmet** [comment]
@jmax01 Hi! Any news on this? We'll be interested in integrating a JaCoCo configuration if you're willing to contribute it.

As mentioned by Gunnar, we'll need a signed CLA to integrate your patches.

Thanks!

**Comment by jmax01** [comment]
Sorry been on vacation.
I will knock it out tomorrow.

**Comment by gsmet** [comment]
@jmax01 ok, cool!

**Comment by gunnarmorling** [comment]
Hey @jmax01, Happy New Year! Do you still plan to follow up on this one?

**Comment by jmax01** [comment]
Whoops slipped my mind of the holidays!

I do have a minimum example ready. 
It appears it needs to be class level annotation to trigger the behavior.

I will post it ASAP.

**Comment by jmax01** [comment]
Update on test creation: Still trying to figure out under what exact conditions $jacocoInit is added to a class.

**Comment by gsmet** [comment]
Hi @jmax01 ,

Still struggling with your test case?

**Comment by jmax01** [comment]
I am getting closer, things need to be "just so" for jacoco to add $jacocoInit to a class.

**Comment by gunnarmorling** [comment]
Hey @jmax01 any further progress with this one?

**Comment by jmax01** [comment]
I finally have a working test.

Since the error depends on classloading and initialization of static fields reproduction is extremely challenging.

For example if the constraint existed in a package that contained the word 'hibernate' the error would not occur thus the package of the test is the issue id.

The test will only run if the jacoco agent is among the InputArguments of the runtime.

```java
package hv1184;

import static java.lang.annotation.ElementType.*;
import static java.lang.annotation.RetentionPolicy.*;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.management.ManagementFactory;

import javax.validation.Constraint;
import javax.validation.Payload;
import javax.validation.ReportAsSingleViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import javax.validation.constraints.Pattern;
import javax.validation.constraintvalidation.SupportedValidationTarget;
import javax.validation.constraintvalidation.ValidationTarget;

import org.hibernate.validator.parameternameprovider.ReflectionParameterNameProvider;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

/**
 * This test will fail with jacoco agent in eclipse
 */
@SuppressWarnings("javadoc")
public class Hv1184Test {

    @Rule
    public ExpectedException thrown = ExpectedException.none();

    static final ValidatorFactory VALIDATOR_FACTORY = Validation.byDefaultProvider()
        .configure()
        .parameterNameProvider(new ReflectionParameterNameProvider())
        .buildValidatorFactory();

    static final Validator VALIDATOR = VALIDATOR_FACTORY.getValidator();

    @Before
    public void beforeMethod() {

        org.junit.Assume.assumeTrue(startedWithJacoco());

    }

    /**
     * Will return true if there is a javaagent with the string jacoco in the startup arguments.
     *
     * @return true, if successful
     */
    boolean startedWithJacoco() {
        for (String inputArgument : ManagementFactory.getRuntimeMXBean()
            .getInputArguments()) {
            if (inputArgument.startsWith("-javaagent") && inputArgument.contains("jacoco")) {
                return true;
            }
        }
        return false;
    }

    @Test
    public void jacocoFail() {
        this.thrown.expect(javax.validation.ValidationException.class);
        this.thrown.expectMessage("HV000083: The specified annotation defines no parameter '$jacocoInit'.");
        try {
            VALIDATOR.validate(new Hv1184Test.Bar("999"));
        } catch (RuntimeException re) {
            throw re;
        }
    }

    public static class Bar {

        @hv1184.Hv1184Test.Hv1184Constraint
        private final String field;

        public Bar(String field) {
            super();
            this.field = field;
        }

    }

    /**
     * Hv1184Constraint constraint.
     * Tests did work when in org.hibernate package structure.
     */
    @Pattern(regexp = Hv1184Constraint.REGEX)
    @Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE })
    @Retention(RetentionPolicy.RUNTIME)
    @Documented
    @Constraint(validatedBy = {})
    @SupportedValidationTarget(ValidationTarget.ANNOTATED_ELEMENT)
    @ReportAsSingleViolation
    public @interface Hv1184Constraint {

        /** The bar regular expression. */
        static String REGEX = "[0-9]{3}";

        /**
         * The bar regular expression pattern.
         * This is required to cause issues with jacococ
         */
        static java.util.regex.Pattern REGEX_PATTERN = java.util.regex.Pattern.compile(REGEX);

        /**
         * Message.
         *
         * @return the string
         *
         */
        String message() default "A bar.field must be 3 digits, was '${validatedValue}'.";

        /**
         * Groups.
         *
         * @return the class[]
         */
        Class<?>[] groups() default {};

        /**
         * Payload.
         *
         * @return the class extends payload[]
         */
        Class<? extends Payload>[] payload() default {};

        /**
         * Defines several {@link Hv1184Constraint} annotations on the same element.
         *
         * @see Hv1184Constraint
         */
        @Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE })
        @Retention(RUNTIME)
        @Documented
        @interface List {

            /**
             * Value.
             *
             * @return the BreaksJacoco[]
             */
            Hv1184Constraint[] value();
        }
    }
}

```

**Comment by jmax01** [comment]
FYI I signed the CLA

**Comment by whiskeysierra** [comment]
Any chance to get this merged?

**Comment by gsmet** [comment]
Rebased and merged! Thanks!

**Comment by jmax01** [comment]
Thanks.

**Pull request closed without merging**
