### PR TITLE
HV-1478 Integration test for OSGi/CDI on Felix/Payara

### PR DESCRIPTION
**Pull request by arjantijms**
HV-1478 Test that specifically tests whether the hibernate-validator-cdi jar's OSGi headers are correct, Felix is able to process them and startup, and then an actual CDI and BV test is able to pass.

Note that to pass this depends on the work done in https://github.com/hibernate/hibernate-validator/pull/846

### CODE REVIEW

**Comment by gunnarmorling** [comment]
ok to test

**Comment by gsmet** [comment]
@arjantijms looks like there is a test failure:

```
Failed tests: 
  CDITest.testAll9Invalid Expected test to throw exception with message a string containing "invalid number"

Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by arjantijms** [comment]
@gsmet 
>looks like there is a test failure:

If the test is executed against Hibernate Validator without https://github.com/hibernate/hibernate-validator/pull/846 applied this is expected, since it will not load the CDI extension with that version and thus not throw the expected exception.

But if 846 was applied and tested with this I'll need to check again.

**Comment by gsmet** [comment]
Ah sure, sorry about that :). I'll take another look tomorrow morning!

**Comment by gsmet** [comment]
Closing in favor of https://github.com/hibernate/hibernate-validator/pull/851 .

**Pull request closed without merging**
