### PR TITLE
HV-995 Update documentation to contain Google Analytics code

### PR DESCRIPTION
**Pull request by emmanuelbernard**
Basically a copy of the Hibernate Search code.

### CODE REVIEW

**Comment by hferentschik** [comment]
rebased and merged

**Comment by gunnarmorling** [comment]
Ah, was just about to do the same. Do you plan to look into any further
PRs, @hferentschik? Just that we do not interfere :)

2015-09-22 9:31 GMT+02:00 Hardy Ferentschik <notifications@github.com>:

**Comment by hferentschik** [comment]
> Do you plan to look into any further PRs

While in the process of catching up with things, yes

**Comment by gunnarmorling** [comment]
Ok, then you do it. No need for us to do it twice ;)

2015-09-22 9:55 GMT+02:00 Hardy Ferentschik <notifications@github.com>:

**Pull request closed without merging**
