### PR TITLE
Added Dutch validation messages

### PR DESCRIPTION
**Pull request by Maurice-Betzel**
* https://hibernate.atlassian.net/browse/HV-1612

### CODE REVIEW

**Comment by gunnarmorling** [comment]
ok to test

**Comment by gsmet** [comment]
Hi @Maurice-Betzel ,

Thanks for your contribution! Minor nitpick: could we be consistent and not have leading capitals on some of the messages? I would fix it myself but I was wondering if maybe `Script` needed a capital in Dutch?

I just saw that the English validation messages are not consistent either, I suppose you followed what we did there, I'll go fix that.

Waiting for your feedback on this, will merge after that.

Thanks!

**Comment by Maurice-Betzel** [comment]
Indeed, i just followed the default. Are you fixing the dutch props as well?

**Comment by gsmet** [comment]
If you confirm me that `Script` can be lowercase too, I will amend your commit. Just checking as I know some languages have some weird rules about casing.

**Comment by Maurice-Betzel** [comment]
No special rules apply, we can keep it analog to the default.

**Comment by gsmet** [comment]
OK, cool, thanks for the confirmation.

**Comment by gsmet** [comment]
Merged, thanks! I will make a global pass on case afterwards.

**Pull request closed without merging**
