### PR TITLE
HV-1224 Changing group id to "org.hibernate.validator"

### PR DESCRIPTION
**Pull request by gunnarmorling**

### CODE REVIEW

**Comment by gsmet** [comment]
@gunnarmorling I pushed another commit with the relocation artifacts. Could you take a look at it?

Thanks.

**Comment by gunnarmorling** [comment]
@gsmet We also should add it for the Karaf features file.

**Comment by gsmet** [comment]
Force pushed an update with the karaf-features stuff.

**Comment by gunnarmorling** [comment]
@gsmet Pushed another commit for making the artifact names more concise.

**Comment by gsmet** [comment]
Squashed the last 2 commits and merged, thanks!

**Pull request closed without merging**
