### PR TITLE
HV-763 Removing redundant logging method

### PR DESCRIPTION
**Pull request by gunnarmorling**
Small left-over from https://hibernate.atlassian.net/browse/HV-763.

### CODE REVIEW

**Comment by gsmet** [comment]
Merged! Thanks!

(still not convinced your automatic replacement of diamonds is a good idea)

**Comment by gunnarmorling** [comment]
> (still not convinced your automatic replacement of diamonds is a good
idea)

But that one wasn't meant to be backported, so it should be fine?

**Comment by gsmet** [comment]
Sure. But it makes each patch less readable.

**Comment by gunnarmorling** [comment]
Ok, now I see that this is your concern. I feel it's digestable if it's
just a small number (similar to import re-org), but I could do separate
commits if you prefer it?

**Pull request merged**
