### PR TITLE
StackOverflowError with HibernateValidator 6.0.13Final when use validator.validate(parameterValues)

### PR DESCRIPTION
**Pull request by lidong14**
when the process working for two days，StackOverflowError always happens 。our code is below：
 validator = Validation.byDefaultProvider()
                .providerResolver(new OsgiValidationProviderResolver())
                .configure().messageInterpolator(resouce)
                .buildValidatorFactory().getValidator();
Set<ConstraintViolation<Object>> validateResultSets = validator.validate(parameterValues);

our team has view the code，we doubt the following code（ ValueExtractorResolver.java, getRuntimeCompliantValueExtractors） may has some problem in Multithreading，why it always happens for a long time？

private Set<ValueExtractorDescriptor> getRuntimeCompliantValueExtractors(Class<?> runtimeType, Set<ValueExtractorDescriptor> potentialValueExtractorDescriptors) {
		if ( nonContainerTypes.contains( runtimeType ) ) {
			return Collections.emptySet();
		}

		Set<ValueExtractorDescriptor> valueExtractorDescriptors = possibleValueExtractorsByRuntimeType.get( runtimeType );
		if ( valueExtractorDescriptors == null ) {
			//otherwise we just look for maximally specific extractors for the runtime type
			Set<ValueExtractorDescriptor> possibleValueExtractors = potentialValueExtractorDescriptors
					.stream()
					.filter( e -> TypeHelper.isAssignable( e.getContainerType(), runtimeType ) )
					.collect( Collectors.toSet() );

			valueExtractorDescriptors = getMaximallySpecificValueExtractors( possibleValueExtractors );
		}

		if ( valueExtractorDescriptors.isEmpty() ) {
			nonContainerTypes.put( runtimeType, NON_CONTAINER_VALUE );
		}
		else {
			Set<ValueExtractorDescriptor> extractorDescriptorsToCache = CollectionHelper.toImmutableSet( valueExtractorDescriptors );
			possibleValueExtractorsByRuntimeType.put( runtimeType, extractorDescriptorsToCache );
			return extractorDescriptorsToCache;
		}
		ValueExtractorDescriptor v  = null;
		
		
		return valueExtractorDescriptors;
	}

the error stack is below：
at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorResolver.getRuntimeCompliantValueExtractors(ValueExtractorResolver.java:316)
        at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorResolver.getValueExtractorCandidatesForContainerDetectionOfGlobalCascadedValidation(ValueExtractorResolver.java:177)
        at org.hibernate.validator.internal.metadata.aggregated.CascadingMetaDataBuilder.build(CascadingMetaDataBuilder.java:227)
        at org.hibernate.validator.internal.metadata.aggregated.FieldCascadable$Builder.build(FieldCascadable.java:83)
        at org.hibernate.validator.internal.metadata.aggregated.FieldCascadable$Builder.build(FieldCascadable.java:64)
        at org.hibernate.validator.internal.metadata.aggregated.PropertyMetaData$Builder.lambda$build$1(PropertyMetaData.java:347)
        at org.hibernate.validator.internal.metadata.aggregated.PropertyMetaData$Builder$$Lambda$62/1651906449.apply(Unknown Source)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.hibernate.validator.internal.metadata.aggregated.PropertyMetaData$Builder.build(PropertyMetaData.java:348)
        at org.hibernate.validator.internal.metadata.aggregated.PropertyMetaData$Builder.build(PropertyMetaData.java:151)
        at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BuilderDelegate.build(BeanMetaDataImpl.java:784)
        at org.hibernate.validator.internal.metadata.aggregated.BeanMetaDataImpl$BeanMetaDataBuilder.build(BeanMetaDataImpl.java:648)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:192)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.lambda$getBeanMetaData$0(BeanMetaDataManager.java:160)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager$$Lambda$53/253243426.apply(Unknown Source)
        at java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:324)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getBeanMetaData(BeanMetaDataManager.java:159)
        at org.hibernate.validator.internal.engine.ValidationContext$ValidationContextBuilder.forValidate(ValidationContext.java:566)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:155)

2018-12-22 09:33:42,301 ERROR [http-nio-auto-1-exec-12][ROOT][ 189] 
java.lang.StackOverflowError
        at java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1031)
       at java.util.Collections$UnmodifiableCollection.isEmpty(Collections.java:1031)

### CODE REVIEW

**Comment by lidong14** [comment]
@marko-bekhta @Maurice-Betzel @gsmet  we doubt that when a thread run CollectionHelper.toImmutableSet，then valueExtractorDescriptors become UnmodifiableCollection. another thread run the valueExtractorDescriptors.isEmpty(), it happens recursion error.

**Comment by gsmet** [comment]
Hi @lidong14 ,

Could you please open an issue on our JIRA here https://hibernate.atlassian.net/secure/Dashboard.jspa and not a PR with random commits?

Other than that, we would also need the stacktrace leading to the SO: I see two stacktraces in your message and can't see the SO clearly. The first one is the start of the second one? Having a good portion of the stack trace in order would help.

From your last lines, it looks as if the unmodifiable collection had wrapped itself, which doesn't look like possible.

Could you also say which JDK you are using?

**Comment by lidong14** [comment]
@gsmet thanks,  we has report the issuse.
https://hibernate.atlassian.net/projects/HV/issues/HV-1684?filter=allopenissues

**Comment by gsmet** [comment]
Closing, fix is there: https://github.com/hibernate/hibernate-validator/pull/1009

**Pull request closed without merging**
