### PR TITLE
Update ValidationMessages_es.properties

### PR DESCRIPTION
**Pull request by Hilmerc**
Adding  6 properties for Spanish, 4 of those are in engine/src/main/resources/org/hibernate/validator/ValidationMessages.properties
2 of those aren't:
javax.validation.constraints.PastOrPresent.message and javax.validation.constraints.FutureOrPresent.message  
but are using from javax/validation/constraints. I will add these to ValidationMessages.properties too

### CODE REVIEW

**Comment by Hilmerc** [comment]
add to whitelist


________________________________

**Comment by gunnarmorling** [comment]
Ok to test

**Comment by gsmet** [comment]
@Hilmerc good catch.

I won't use your error messages as they are defined in the spec so I'm gonna use the ones from the spec but thanks for the report!

**Comment by gsmet** [comment]
Closed the wrong one (just got back from vacation...).

@Hilmerc  Thanks for this update! I created a JIRA issue to track this one: https://hibernate.atlassian.net/browse/HV-1452 .

Could you update the OrPresent translations to be consistent with the English ones:
```
javax.validation.constraints.FutureOrPresent.message = must be a date in the present or in the future
javax.validation.constraints.PastOrPresent.message   = must be a date in the past or in the present
```

Today is not a good translation as in the case of a `Year` type, present will mean the whole year.

Could you also sign the CLA for the Hibernate Validator project here: https://cla.jboss.org/ and get back to me with the user name you used?

Thanks!

**Comment by Hilmerc** [comment]
I created the user: hilmerc  with my e-mail hilac@msn.com, and I updated the two properties

**Comment by gsmet** [comment]
@Hilmerc we can't find you on the CLA application. Did you sign the CLA for Hibernate Validator?

Thanks!

**Comment by Hilmerc** [comment]
I signed the CLA some minutes ago.

**Comment by gsmet** [comment]
@Hilmerc I merged your commits into one and reformatted the file. It will be part of 6.0.0.Final. Thanks!

**Pull request closed without merging**
