### PR TITLE
HV-1462 Provide patch file for WildFly 11 Beta1

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/HV-1462

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM; the only thing would be to re-word the [reference guide section](http://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_updating_hibernate_validator_in_wildfly) on the WF modules so it covers 10 and 11.

**Comment by gsmet** [comment]
Yeah, tbh, it was intentional as I didn't want to add information about the development version of WF. I'll propose something.

**Comment by gsmet** [comment]
@gunnarmorling done

**Comment by gunnarmorling** [comment]
Thanks!

**Pull request merged**
