### PR TITLE
Give more memory to the JVM for OSGi tests [don't merge, please]

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by DavideD** [comment]
Jenkins, retest this please

**Comment by gsmet** [comment]
Jenkins, retest this please

**Comment by gunnarmorling** [comment]
Hey @gsmet, what shall we do with this PR? Can we close it?

**Pull request closed without merging**
