### PR TITLE
HV-1884 Composing constraints order is unpredictable

### PR DESCRIPTION
**Pull request by Katalystical**
[https://hibernate.atlassian.net/browse/HV-1884](https://hibernate.atlassian.net/browse/HV-1884)

### CODE REVIEW

**Comment by Katalystical** [comment]
(From https://github.com/hibernate/hibernate-validator/pull/1223#issuecomment-1035956431):

> Note the build failure is on the JDK 8 build, which also fails on the main branch. This is an unrelated problem which should be fixed by https://github.com/hibernate/hibernate-validator/pull/1219 .

**Comment by gsmet** [comment]
I pushed a rebase.

**Comment by gsmet** [comment]
Thanks!

**Comment by Katalystical** [comment]
De rien, I've got to thank you, having a PR merged this soon seems to be tricky in certain other OSS projects. Are you also backporting it to 6.2? @gsmet

**Pull request merged**
