### PR TITLE
HV-1781 Fix Jakarta Persistence class presence test

### PR DESCRIPTION
**Pull request by jGauravGupta**
Signed-off-by: Gaurav Gupta <gaurav.gupta@payara.fish>

https://hibernate.atlassian.net/browse/HV-1781

### CODE REVIEW

**Comment by gsmet** [comment]
Good catch! I amended the commit to include a JIRA number into the comment.

**Comment by gsmet** [comment]
@jGauravGupta do you have more fixes coming or should I release an Alpha3 with this fix?

**Comment by jGauravGupta** [comment]
Thanks @gsmet, Yes please release Alpha3.

**Comment by gsmet** [comment]
@jGauravGupta OK, I pushed the release. It needs to be synced to Maven Central, should be done by tomorrow.

**Comment by gsmet** [comment]
@jGauravGupta the artifacts are on Maven Central. Thanks again for the fix!

Our JPA tests are based on Hibernate ORM and I don't have a `jakarta.*` version of it so I was unable to properly test it.

**Pull request merged**
