### PR TITLE
HV-1739 - HV-1740 - Assorted changes related to @SafeHtml

### PR DESCRIPTION
**Pull request by gsmet**

### CODE REVIEW

**Comment by sepe81** [comment]
Is there any recommended replacement for the now deprecated SafeHtml annotation?

**Comment by gsmet** [comment]
I'm long overdue on the announcement, will write something tomorrow.

**Comment by rafollett** [comment]
@gsmet will this fix also be applied to the hibernate 5 version? Would be beneficial for my Grails application that leverages this currently

**Comment by gsmet** [comment]
@rafollett we don't plan on releasing any community 5.x in the future.

You could try to upgrade to 6, in most cases, it's a drop in replacement.

**Pull request merged**
