### PR TITLE
HV-1100 Convert the reference guide to use source includes

### PR DESCRIPTION
**Pull request by gsmet**
This one is on top of https://github.com/hibernate/hibernate-validator/pull/512 .

 * https://hibernate.atlassian.net/browse/HV-1100

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@gsmet do you have any idea why that removes so many more lines than it adds? On first thought I'd have said that the extraction should be neutral in terms of lines (give or take).

**Comment by gsmet** [comment]
Well, not in this case, as most of the sources were already extracted. I just had to point to them (well and check they were effectively in sync).

I extracted a few classes but not much.

**Comment by gunnarmorling** [comment]
Ok, makes sense then :)

**Comment by gunnarmorling** [comment]
Rebased and applied. It's very hard to compare the actual files, I trust you did the right thing, @gsmet :)

**Pull request closed without merging**
