### PR TITLE
HV-1451 Add @PastOrPresent and @FutureOrPresent messages

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/HV-1451

Should also be merged to 6.0.0-build-branch.

### CODE REVIEW

**Comment by gsmet** [comment]
@marko-bekhta @gunnarmorling Could you push the Ukrainian and German translations to this PR?

**Comment by marko-bekhta** [comment]
@gsmet done :)

**Comment by gsmet** [comment]
Force pushed a test update.

**Comment by gunnarmorling** [comment]
@gsmet done.

**Comment by gsmet** [comment]
Rebased and merged, thanks!

**Pull request closed without merging**
