### PR TITLE
HV-1512 Improve initialization cost of all logger classes

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HV-1512

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Jenkins, retest this, please.

**Comment by gunnarmorling** [comment]
Jenkins, retest this, please.

**Comment by gunnarmorling** [comment]
LGTM, just waiting for the CI build.

**Comment by gsmet** [comment]
@Sanne out of curiosity, where does it come from? Does it make a significant difference?

**Comment by Sanne** [comment]
> @Sanne out of curiosity, where does it come from? Does it make a significant difference?

It's coming from you mentioning on the blog that we're slower to initialize. It reminded me that I had this idea in mind and never did it.

Yes it makes a very significant difference, but only on class initialization of the whole framework.

**Comment by gunnarmorling** [comment]
Applied. Thanks, @Sanne!

**Comment by Sanne** [comment]
Some more data; I run the testsuite using surefire's options reuseForks=false and forkCount=1 to ensure each test would run in a new fresh JVM.

after the patch: Total time: 05:06 min
before the patch: Total time: 06:39 min

That's quite good!

**Comment by gunnarmorling** [comment]
Ok, but that's rather unrealistic, no one is going to reload their HV classes after using a validator factory just once ;) Still a very good improvement. Perhaps do the same for OGM? Don't expect such big difference there, but it's less hack-ish since the security manager subclass trick.

**Comment by Sanne** [comment]
Sure I'm aware it's unrealistic, but knowing this would benefit exclusively the "cold boot" I think it's the only sensible way to measure if it makes sense at all.

I'm not shy to admit though that I'm interested in exploring such things more regularly to bring the "tool bootstrap time" down for e.g. the WildFly bootstrap time but also the "perception" people have of stuff being "not light". Totally agree that it makes not much sense for the _real_ value.

**Pull request merged**
