### PR TITLE
HV-1034 Make HV build on JDK 9

### PR DESCRIPTION
**Pull request by hferentschik**
Follow up to #458

### CODE REVIEW

**Comment by hferentschik** [comment]
Ok, I attached the debugger and found two more info diagnostic messages in the returned diagnostic instance (on top of the two expected errors). They are:

    Note: annotation-processor/src/test/java/org/hibernate/validator/ap/testmodel/ModelWithJodaTypes.java uses or overrides a deprecated API.

and 

    Note: Recompile with -Xlint:deprecation for details.

@gunnarmorling Is this the same error you have been seeing? Any clue?

**Comment by hferentschik** [comment]
@gunnarmorling - Ok, if I understand correctly the problem is with `ModelWithJodaTypes` and the use of `DateMidnight`. I can see you added `@SuppressWarnings("deprecation")`. Does this solve the issue for you?

BTW, what java version are you using and which OS. I am OS X and

    java version "1.9.0-ea"
    Java(TM) SE Runtime Environment (build 1.9.0-ea-b39)
    Java HotSpot(TM) 64-Bit Server VM (build 1.9.0-ea-b39, mixed mode)

**Comment by hferentschik** [comment]
Apart of trying to understand why this seems to work for you and not me, we could just remove `public DateMidnight jodaDateMidnight;`, no? From a test perspective it should not make a difference.

**Comment by hferentschik** [comment]
Same applies for `HibernateValidatorProvidedCustomConstraints`. Funny enough just having an import statement with the deprecated type causes this error. `SupressWarnings` or not.

**Comment by hferentschik** [comment]
@gunnarmorling Here is the next issue. If I for now remove the deprecates types, the build continues, but fails on the OSGi integration tests:

    Running org.hibernate.validator.osgi.integrationtest.OsgiIntegrationTest
    Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 181.724 sec <<<     FAILURE! - in org.hibernate.validator.osgi.integrationtest.OsgiIntegrationTest
    org.hibernate.validator.osgi.integrationtest.OsgiIntegrationTest  Time elapsed:     181.615 sec  <<< ERROR!
    java.lang.RuntimeException: Cannot get the remote bundle context
    	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.    getRemoteBundleContext(RemoteBundleContextClientImpl.java:255)
    	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.waitForState    (RemoteBundleContextClientImpl.java:211)
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.waitForState(    KarafTestContainer.java:580)
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.startKaraf(    KarafTestContainer.java:230)
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.start(    KarafTestContainer.java:180)
    	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(    EagerSingleStagedReactor.java:86)
    	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(    EagerSingleStagedReactor.java:136)
    	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.    java:448)
    	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
    	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.    java:264)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.    java:153)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(    ForkedBooter.java:200)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.    java:153)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
    Caused by: java.rmi.NotBoundException: 8d47e7b8-81c8-43ca-acd6-a9f8bdfaea43
    	at sun.rmi.registry.RegistryImpl.lookup(RegistryImpl.java:166)
    	at sun.rmi.registry.RegistryImpl_Skel.dispatch(Unknown Source)
    	at sun.rmi.server.UnicastServerRef.oldDispatch(UnicastServerRef.java:408)
    	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:266)
    	at sun.rmi.transport.Transport$1.run(Transport.java:179)
    	at sun.rmi.transport.Transport$1.run(Transport.java:176)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at sun.rmi.transport.Transport.serviceCall(Transport.java:175)
    	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:553)
    	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.    java:808)
    	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:667)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    	at sun.rmi.transport.StreamRemoteCall.exceptionReceivedFromServer(StreamRemoteCall    .java:276)
    	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:253)
    	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:379)
    	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
    	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.    getRemoteBundleContext(RemoteBundleContextClientImpl.java:242)
    	at org.ops4j.pax.exam.rbc.client.intern.RemoteBundleContextClientImpl.waitForState    (RemoteBundleContextClientImpl.java:211)
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.waitForState(    KarafTestContainer.java:580)
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.startKaraf(    KarafTestContainer.java:230)
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.start(    KarafTestContainer.java:180)
    	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.setUp(    EagerSingleStagedReactor.java:86)
    	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.beforeClass(    EagerSingleStagedReactor.java:136)
    	at org.ops4j.pax.exam.spi.reactors.ReactorManager.beforeClass(ReactorManager.    java:448)
    	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:97)
    	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.    java:264)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.    java:153)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(    ForkedBooter.java:200)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.    java:153)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
    
    org.hibernate.validator.osgi.integrationtest.OsgiIntegrationTest  Time elapsed:     181.724 sec  <<< ERROR!
    java.lang.RuntimeException: Container never came up
    	at org.ops4j.pax.exam.karaf.container.internal.KarafTestContainer.stop(    KarafTestContainer.java:550)
    	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.tearDown(    EagerSingleStagedReactor.java:118)
    	at org.ops4j.pax.exam.spi.reactors.EagerSingleStagedReactor.afterClass(    EagerSingleStagedReactor.java:132)
    	at org.ops4j.pax.exam.spi.reactors.ReactorManager.afterClass(ReactorManager.    java:432)
    	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:107)
    	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.    java:264)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.    java:153)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    
    
    Results :
    
    Tests in error: 
      OsgiIntegrationTest.org.hibernate.validator.osgi.integrationtest.    OsgiIntegrationTest » Runtime
      JUnit4Provider.invoke:124->executeTestSet:153->execute:264 » Runtime Container...
    
    Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

So this passes for you as well?

**Comment by hferentschik** [comment]
Regarding the annotation processor, I tried to add `options.add("-Xlint:-deprecation");` to the compilation options and the warning still persists. Looks like there is a JDK bug imo.

**Comment by gunnarmorling** [comment]
> I can see you added @SuppressWarnings("deprecation"). Does this solve the issue for you?

Yes, it does. I suppose due to a newer version:

> BTW, what java version are you using and which OS

I am on build 101 (also OS X):

    java version "9-ea"
    Java(TM) SE Runtime Environment (build 9-ea+101-2016-01-13-175626.javare.4276.nc)
    Java HotSpot(TM) 64-Bit Server VM (build 9-ea+101-2016-01-13-175626.javare.4276.nc, mixed mode)

> Apart of trying to understand why this seems to work for you and not me, we could just remove public DateMidnight jodaDateMidnight;, no? 

I guess we could, but then we'd limit the test. We want to make sure the AP doesn't complain about constraints given on actually supported types.

> but fails on the OSGi integration tests

I am seeing that one, too. I attributed it to local issues I am having with the OSGi test, so I didn't care that much. But it seems something different then which we'll need to analyze.

Can you test with a newer build and let me know how it goes? Assuming the AP stuff passes, we could move on, leaving only the OSGi failure left on our plates.

**Comment by hferentschik** [comment]
> Yes, it does. I suppose due to a newer version

I am on the same version than you - 101

**Comment by gunnarmorling** [comment]
> I am on the same version than you - 101

Ok, so you upgraded from build 1.9.0-ea-b39 to 101 and it still is failing? No idea what's the difference between our envs then. How odd.

**Comment by hferentschik** [comment]
> Ok, so you upgraded from build 1.9.0-ea-b39 to 101 and it still is failing? 

Doh, I might have pointed my symbolic link to the wrong directory. Let me give it another go.

**Comment by hferentschik** [comment]
Ok, now I am actually at the same point as you. Remaining issue are the OSGi tests. I agree we can at least merge the compilation issues and create a follow up issue for the OSGi tests. Doing it now.

**Comment by gunnarmorling** [comment]
Nice :)

**Comment by hferentschik** [comment]
Merged and created https://hibernate.atlassian.net/browse/HV-1051 as follow up.

**Pull request closed without merging**
