### PR TITLE
HV-1222 Update CollectionHelper.iteratorFromArray and add CollectionHelper.iterableFromArray

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HV-1222

This basically adds what was already added in Search: https://github.com/hibernate/hibernate-search/commit/1b3c001011f10b410b6f8b208e5ba58cf9b15fc9

I'm not sure the second commit is really necessary, but I added it anyway so you have the choice to merge it or not.

### CODE REVIEW

**Comment by yrodiere** [comment]
@gsmet  Just fixed the checkstyled issue... Sorry

**Comment by yrodiere** [comment]
@gunnarmorling Done, I updated the JIRA. Does it seem ok to you?

**Comment by gunnarmorling** [comment]
Merged; thanks, @yrodiere!

**Comment by gunnarmorling** [comment]
Merged; thanks, @yrodiere!

**Pull request merged**
