### PR TITLE
HV-1235 Fixing mentioning of NIP in PESEL's javadoc

### PR DESCRIPTION
**Pull request by michalfotyga**

### CODE REVIEW

**Comment by gsmet** [comment]
ok to test

**Comment by gsmet** [comment]
@michalfotyga good catch! Could you sign the CLA at https://cla.jboss.org/index.seam for the Hibernate Validator project and get back to us with the username you used there?

Thanks!

**Comment by michalfotyga** [comment]
Thanks @gsmet ! 😉 
Have started the CLA signing process yesterday but am still waiting for the application to be accepted. My user id is **michal.fotyga**

**Comment by gsmet** [comment]
Yeah, Emmanuel who validates the CLA is on vacation this week so we'll have to wait until Monday. I'll ping him on Monday.

**Comment by gsmet** [comment]
But I'll merge this right away.

Thanks!

**Comment by michalfotyga** [comment]
Thank you, what a nice way to start a day 😄

**Pull request closed without merging**
