### PR TITLE
HV-1611 Be consistent in the case of the validation messages

### PR DESCRIPTION
**Pull request by gsmet**
* https://hibernate.atlassian.net/browse/HV-1611

@marko-bekhta not the most interesting PR but would appreciate a quick check. Thanks!

### CODE REVIEW

**Comment by marko-bekhta** [comment]
@gsmet the changed ones looks good. As for the rest - I suppose the ones in DE file should be with uppercase (e.g. Skriptausdruck), and also MN and RU ones have first words with uppercase chars. Do we need to change them ?

**Comment by gsmet** [comment]
Yeah, German loves capitals. As for RU and MN, I'm not familiar with them so I refrained from doing any change.

Changes welcome if you're confident we should change them.

**Comment by marko-bekhta** [comment]
well I don't know the Mongolian, but at least all the messages there start with a capital letter. So they are consistent. Updated a few lines from the Ru file. You can just squash them into your commit so it'll be cleaner.

**Comment by gsmet** [comment]
OK, cool, thanks. Done and merged!

**Pull request closed without merging**
